routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::name('manage.')->group(function () {
    Route::prefix('manage')->group(function () {
        //Users Routes
        Route::get('users', 'UserManagementController@users')->name('users');
        Route::get('users/add', 'UserManagementController@add_user')->name('user.add');
        Route::post('users/save', 'UserManagementController@save_user')->name('user.save');
        Route::get('user/{id}', 'UserManagementController@view_user')->name('user.view');
        Route::get('user/{id}/edit', 'UserManagementController@edit_user')->name('user.edit');
        Route::put('user/{id}/update', 'UserManagementController@update_user')->name('user.update');
        Route::delete('user/{id}/delete', 'UserManagementController@delete_user')->name('user.delete');
        Route::get('user/{id}/permissions', 'UserManagementController@permissions_user')->name('user.permissions');
        Route::get('user/{id}/roles', 'UserManagementController@roles_user')->name('user.roles');
        Route::post('user/{id}/permissions', 'UserManagementController@save_permissions_user')->name('user.permissions.save');
        Route::post('user/{id}/roles', 'UserManagementController@save_roles_user')->name('user.roles.save');

        //Permissions Routes
        Route::get('permissions', 'UserManagementController@permissions')->name('permissions');
        Route::get('permission/add', 'UserManagementController@add_permission')->name('permission.add');
        Route::get('permission/{id}', 'UserManagementController@view_permission')->name('permission.view');
        Route::post('permission/add', 'UserManagementController@save_permission')->name('permission.save');
        Route::get('permission/{id}/edit', 'UserManagementController@edit_permission')->name('permission.edit');
        Route::put('permission/{id}/update', 'UserManagementController@update_permission')->name('permission.update');
        Route::delete('permission/{id}/delete', 'UserManagementController@delete_permission')->name('permission.delete');

        //Roles Routes
        Route::get('roles', 'UserManagementController@roles')->name('roles');
        Route::get('role/add', 'UserManagementController@add_role')->name('role.add');
        Route::get('role/{id}', 'UserManagementController@view_role')->name('role.view');
        Route::post('role/add', 'UserManagementController@save_role')->name('role.save');
        Route::get('role/{id}/edit', 'UserManagementController@edit_role')->name('role.edit');
        Route::put('role/{id}/update', 'UserManagementController@update_role')->name('role.update');
        Route::delete('role/{id}/delete', 'UserManagementController@delete_role')->name('role.delete');

    });


});
//
//Claimants Routes
Route::get('claimants', 'ClaimantController@getClaimants')->name('claimants');
Route::get('claimants/add', 'ClaimantController@add_claimant')->name('claimant.add');
Route::post('claimants/save', 'ClaimantController@saveClaimant')->name('claimant.save');
Route::get('claimants/{id}', 'ClaimantController@viewClaimant')->name('claimant.view');
Route::delete('claimants/{id}/delete', 'ClaimantController@deleteClaimant')->name('claimant.delete');
Route::get('claimants/{id}/edit', 'ClaimantController@editClaimant')->name('claimant.edit');
Route::put('claimants/{id}/update', 'ClaimantController@updateClaimant')->name('claimant.update');

//      Claims Route
Route::get('claims', 'ClaimsController@getClaims')->name('claims');
Route::post('claims', 'ClaimsController@updateStatus')->name('update_claim_status');
Route::post('process-claims', 'ClaimsController@processClaim')->name('process-claim');
Route::post('approve-claims', 'ClaimsController@approveClaim')->name('approve-claim');
Route::post('decline-claims', 'ClaimsController@declineClaim')->name('decline-claim');
Route::get('claims/{id}', 'ClaimsController@viewClaim')->name('claims.view');

//Broker Route
Route::get('broker', 'BrokerController@getBrokers')->name('brokers');
Route::get('broker/add', 'BrokerController@addBrokers')->name('broker.add');
Route::post('broker/add', 'BrokerController@saveBrokers')->name('broker.save');
Route::get('broker/{id}', 'BrokerController@viewBrokers')->name('broker.view');
Route::delete('broker/{id}/delete', 'BrokerController@deleteBrokers')->name('broker.delete');
Route::get('broker/{id}/edit', 'BrokerController@editBrokers')->name('broker.edit');
Route::put('broker/{id}/update', 'BrokerController@updateBrokers')->name('broker.update');


Route::get('scrape', 'BrokerController@scrapeWeb')->name('scrape');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" data-textdirection="ltr" class="loading">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Aginqua Insurance Management System">
    <meta name="keywords" content="africa, smart, insurance, travel insurance">
    <meta name="author" content="Aginqua">

    <title>{{ config('app.name', 'ICM') }} - Insurance Claims Management System</title>

    <link rel="apple-touch-icon" href="">
    <link rel="shortcut icon" type="image/x-icon" href="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i"
          rel="stylesheet">

    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/vendors.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('vendors/css/extensions/unslider.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('vendors/css/weather-icons/climacons.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('fonts/meteocons/style.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('vendors/css/charts/morris.css') }}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/extensions/toastr.css')}}">
    @stack('vendor-styles')

    <!-- END VENDOR CSS-->

    <!-- BEGIN LARAVEL DEFAULT CSS-->
    {{--<link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">--}}
    <!-- END LARAVEL DEFAULT CSS-->

    <!-- BEGIN STACK CSS-->
    @stack('stack-styles')
    <link rel="stylesheet" type="text/css" href="{{asset('css/plugins/extensions/toastr.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/core/colors/palette-tooltip.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}">
    <!-- END STACK CSS-->






    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/core/menu/menu-types/horizontal-menu.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('fonts/simple-line-icons/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/core/colors/palette-gradient.css') }}">
    <link rel="stylesheet" type="text/css" href=" {{ asset('css/pages/timeline.css') }}">
    @stack('page-styles')
    <!-- END Page Level CSS-->

    <!-- BEGIN Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('custom-assets/css/style.css') }}">
    <!-- END Custom CSS-->

</head>
<body data-open="click" data-menu="horizontal-menu" data-col="2-columns" class="horizontal-layout horizontal-menu 2-columns   menu-expanded">

<!-- fixed-top -->
@include('layouts.topbar')
<!-- end fixed-top -->


<!-- Horizontal navigation-->
@include('layouts.menubar')
<!-- Horizontal navigation-->


<main class="app-content container center-layout mt-2">
    <div class="content-wrapper" style="min-height: 600px">
        @yield('content')
    </div>
</main>


@include('layouts.footer')

<!-- BEGIN LARAVEL DEFAULT JS -->
{{--<script src="{{ asset('js/app.js') }}" defer></script>--}}
<!-- END LARAVEL DEFAULT JS-->

<!-- BEGIN VENDOR JS-->
<script src="{{ asset('vendors/js/vendors.min.js') }}" type="text/javascript"></script>
<!-- BEGIN VENDOR JS-->

<!-- BEGIN PAGE VENDOR JS-->
<script type="text/javascript" src="{{ asset('vendors/js/ui/jquery.sticky.js') }}"></script>
<script type="text/javascript" src="{{ asset('vendors/js/charts/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('vendors/js/charts/raphael-min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/js/charts/morris.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/js/extensions/unslider-min.js') }}" type="text/javascript"></script>
<script src="{{ asset('vendors/js/timeline/horizontal-timeline.js')}}" type="text/javascript"></script>
@stack('vendor-script')
<!-- END PAGE VENDOR JS-->

<!-- BEGIN STACK JS-->
<script src="{{ asset('js/core/app-menu.js')}}" type="text/javascript"></script>
<script src="{{ asset('js/core/app.js')}}" type="text/javascript"></script>
<!-- END STACK JS-->


<!-- BEGIN PAGE LEVEL JS-->
<script type="text/javascript" src="{{ asset('js/scripts/ui/breadcrumbs-with-stats.js')}}"></script>
<script src="{{ asset('js/scripts/pages/dashboard-ecommerce.js')}}" type="text/javascript"></script>
<!-- END PAGE LEVEL JS-->
@stack('stack-script')


@stack('plugins')


@if(session()->has('notification'))
    @component('layouts.toast-notification')
    @endcomponent
@endif

</body>
</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" data-textdirection="ltr" class="loading">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Aginqua Insurance Management System">
    <meta name="keywords" content="africa, smart, insurance, travel insurance">
    <meta name="author" content="Aginqua">

    <title>{{ config('app.name', 'Aginqua') }} - Africa's Smart Travel Insurance</title>

    <link rel="apple-touch-icon" href="{{ asset('images/logo/a_aginqua_80x80.png') }}">
    <link rel="shortcut icon" type="image/x-icon" href="{{ asset('images/logo/a_aginqua_80x80.png') }}">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i"
          rel="stylesheet">

    <link rel="stylesheet" type="text/css" href={{asset('css/tables/datatable/datatables.min.css')}}>


    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/vendors.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/forms/icheck/icheck.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('vendors/css/forms/icheck/custom.css')}}">
    <!-- END VENDOR CSS-->

    <!-- BEGIN STACK CSS-->
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}">
    <!-- END STACK CSS-->

    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/core/menu/menu-types/vertical-menu-modern.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/core/colors/palette-gradient.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('css/pages/login-register.css')}}">
    <!-- END Page Level CSS-->
    <!-- BEGIN Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('css/style.css')}}">
@section('styles')
@show
<!-- END Custom CSS-->
</head>
<body class="horizontal-layout horizontal-menu 1-column   menu-expanded blank-page blank-page"
      data-open="click" data-menu="horizontal-menu" data-col="1-column">





<div class="app-content container center-layout mt-2">
    <div class="content-wrapper">

        @yield('content')

    </div>
</div>

















<!-- ////////////////////////////////////////////////////////////////////////////-->
<!-- BEGIN VENDOR JS-->
<script src="{{asset('vendors/js/vendors.min.js')}}" type="text/javascript"></script>
<!-- BEGIN VENDOR JS-->
<!-- BEGIN PAGE VENDOR JS-->
<script src="{{asset('vendors/js/forms/icheck/icheck.min.js')}}" type="text/javascript"></script>
<script src="{{asset('vendors/js/forms/validation/jqBootstrapValidation.js')}}"
        type="text/javascript"></script>
<!-- END PAGE VENDOR JS-->
<script src={{asset('js/tables/datatable/datatables.min.js')}} type="text/javascript"></script>

<script src={{asset('js/scripts/tables/datatables/datatable-basic.js')}}
        type="text/javascript"></script>


<!-- BEGIN STACK JS-->
<script src="{{asset('js/core/app-menu.js')}}" type="text/javascript"></script>
<script src="{{asset('js/core/app.js')}}" type="text/javascript"></script>
<script src="{{asset('js/scripts/customizer.js')}}" type="text/javascript"></script>
<!-- END STACK JS-->
<!-- BEGIN PAGE LEVEL JS-->
<script src="{{asset('js/scripts/forms/form-login-register.js')}}" type="text/javascript"></script>
<!-- END PAGE LEVEL JS-->

@stack('plugins')

</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer footer-static footer-light navbar-shadow">
    <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2 container center-layout">
      <span class="float-md-left d-block d-md-inline-block">Copyright &copy; 2018
          <a href="#" target="_blank" class="text-bold-800 grey darken-2">ICM </a>, All rights reserved.
      </span>
    </p>
</footer>

resources/views/layouts/menubar.blade.php
<!-- Horizontal navigation-->
<div role="navigation" data-menu="menu-wrapper" class="header-navbar navbar-expand-sm navbar navbar-horizontal navbar-fixed navbar-light navbar-without-dd-arrow navbar-shadow menu-border">
    <!-- Horizontal menu content-->
    <div data-menu="menu-container" class="navbar-container main-menu-content container center-layout">
        <ul id="main-menu-navigation" data-menu="menu-navigation" class="nav navbar-nav">
            <li data-menu="dropdown" class="dropdown nav-item" style="margin-right: 10px">
                <a href="{{ route('home') }}" class="nav-link"><i class="ft-home"></i>
                    <span>Dashboard</span>
                </a>
                <ul class="dropdown-menu">
                    <li data-menu="" class=""><a href="{{ url('/') }}">Dashboard</a></li>
                </ul>
            </li>
            <li data-menu="dropdown" class="dropdown nav-item" style="margin-right: 10px">
                <a href="{{route('claimants')}}" class="nav-link"><i class="ft-users"></i>
                    <span>Claimants</span>
                </a>
            </li>
            <li data-menu="dropdown" class="dropdown nav-item" style="margin-right: 10px">
                <a href="{{route('claims')}}" class="nav-link"><i class="ft-file-text"></i>
                    <span>Claims</span>
                </a>
            </li>
            <li data-menu="dropdown" class="dropdown nav-item" style="margin-right: 10px">
                <a href="{{route('brokers')}}" class="nav-link"><i class="ft-users"></i>
                    <span>Brokers</span>
                </a>
            </li>

            <li data-menu="dropdown" class="dropdown nav-item" style="margin-right: 10px">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link"><i class="ft-user-check"></i>
                    <span>User Management</span>
                </a>
                <ul class="dropdown-menu">
                    <li data-menu="" class=""><a href="{{route('manage.users')}}" data-toggle="dropdown" class="dropdown-item">System Users</a>
                    </li>
                    <li data-menu="" class=""><a href="{{route('manage.roles')}}" data-toggle="dropdown" class="dropdown-item">Roles</a>
                    </li>
                    <li data-menu="" class=""><a href="{{route('manage.permissions')}}" data-toggle="dropdown" class="dropdown-item">Permissions</a>
                    </li>
                </ul>
            </li>

            <li data-menu="dropdown" class="dropdown nav-item">
                <a href="{{ url('/') }}" data-toggle="dropdown" class="dropdown-toggle nav-link"><i class="ft-settings"></i>
                    <span>System Settings</span>
                </a>
                <ul class="dropdown-menu">
                    <li data-menu="" class=""><a href="" data-toggle="dropdown" class="dropdown-item">Coming Soon</a>
                    </li>
                    <li data-menu=""><a href="" data-toggle="dropdown" class="dropdown-item">Coming Soon</a>
                    </li>
                    <li data-menu=""><a href="" data-toggle="dropdown" class="dropdown-item">Coming Soon</a>
                    </li>
                </ul>
            </li>

        </ul>
    </div>
    <!-- /horizontal menu content-->
</div>
<!-- Horizontal navigation-->

resources/views/layouts/toast-notification.blade.php
<script src="{{ asset('vendors/js/extensions/toastr.min.js') }}" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {

        var message = "{{ session()->get("notification.message", "") }}".replace(/@@@/g , "<br><br>");
        var type = "{{ session()->get("notification.type", "info") }}";
        var title = "{{ session()->get("notification.title", "") }}";

            toastr[type](message, title, {
                positionClass: 'toast-top-{{ session()->get("notification.position", "right") }}',
                "showMethod": "slideDown",
                "hideMethod": "slideUp",
                timeOut: 8000
            });

    });

</script>

resources/views/layouts/topbar.blade.php
<!-- fixed-top-->
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-static-top navbar-dark bg-gradient-x-grey-blue navbar-border navbar-brand-center">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-md-none mr-auto"><a href="#"
                                                                      class="nav-link nav-menu-main menu-toggle hidden-xs"><i
                                class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item">
                    <a href="{{ url('/') }}" class="navbar-brand">
                        <h2 class="brand-text" style="padding-left: 0px">
                            {{--<img alt="aginqua logo" src="" class="brand-logo">--}}
                            ICM
                        </h2>
                    </a>
                </li>
                <li class="nav-item d-md-none">
                    <a data-toggle="collapse" data-target="#navbar-mobile" class="nav-link open-navbar-container">
                        <i class="fa fa-ellipsis-v"></i></a>
                </li>
            </ul>
        </div>
        <div class="navbar-container container center-layout">
            <div id="navbar-mobile" class="collapse navbar-collapse">

                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-md-block"><a href="#" class="nav-link nav-link-expand"><i
                                    class="ficon ft-maximize"></i></a></li>
                </ul>

                <ul class="nav navbar-nav float-right">
                    <li class="dropdown dropdown-notification nav-item">
                        <a href="#" data-toggle="dropdown" class="nav-link nav-link-label"><i class="ficon ft-bell"></i>
                            <span class="badge badge-pill badge-default badge-danger badge-default badge-up">0</span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                            <li class="dropdown-menu-header">
                                <h6 class="dropdown-header m-0">
                                    <span class="grey darken-2">Notifications</span>
                                    <span class="notification-tag badge badge-default badge-danger float-right m-0">0 New</span>
                                </h6>
                            </li>
                            <li class="scrollable-container media-list">
                                {{--<a href="javascript:void(0)">--}}
                                {{--<div class="media">--}}
                                {{--<div class="media-left align-self-center"><i class="ft-file icon-bg-circle bg-teal"></i></div>--}}
                                {{--<div class="media-body">--}}
                                {{--<h6 class="media-heading">Generate monthly report</h6>--}}
                                {{--<small>--}}
                                {{--<time datetime="2015-06-11T18:29:20+08:00" class="media-meta text-muted">Last month</time>--}}
                                {{--</small>--}}
                                {{--</div>--}}
                                {{--</div>--}}
                                {{--</a>--}}
                            </li>
                            <li class="dropdown-menu-footer"><a href="javascript:void(0)"
                                                                class="dropdown-item text-muted text-center">No
                                    notifications found</a></li>
                        </ul>
                    </li>

                    <li class="dropdown dropdown-user nav-item">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link dropdown-user-link">
                            <span class="avatar avatar-online">
                                 <img src="{{ asset('images/portrait/small/avatar-s-1.png') }}" alt="avatar"><i></i>
                            </span>

                            @php
                                if(!empty(Auth::user())) {
                                    $split_name = explode(" ", Auth::user()->name, 2);
                                    $first_name = ucwords($split_name[0]);
                                    $last_name = "";
                                    if (!empty($split_name[1])) {
                                        $last_name = substr( ucwords($split_name[1]), 0,3).".";
                                    }
                                }
                            @endphp

                            <span class="user-name">{{$first_name." ".$last_name}}</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right"><a href="#" class="dropdown-item"><i
                                        class="ft-user"></i> Edit Profile</a>
                            <a href="#" class="dropdown-item"><i class="ft-check-square"></i> Coming Soon</a>
                            <div class="dropdown-divider"></div>

                            <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
                                <i class="ft-power"></i> {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>

                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>