routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::name('manage.')->group(function () {
    Route::prefix('manage')->group(function () {
        //Users Routes
        Route::get('users', 'UserManagementController@users')->name('users');
        Route::get('users/add', 'UserManagementController@add_user')->name('user.add');
        Route::post('users/save', 'UserManagementController@save_user')->name('user.save');
        Route::get('user/{id}', 'UserManagementController@view_user')->name('user.view');
        Route::get('user/{id}/edit', 'UserManagementController@edit_user')->name('user.edit');
        Route::put('user/{id}/update', 'UserManagementController@update_user')->name('user.update');
        Route::delete('user/{id}/delete', 'UserManagementController@delete_user')->name('user.delete');
        Route::get('user/{id}/permissions', 'UserManagementController@permissions_user')->name('user.permissions');
        Route::get('user/{id}/roles', 'UserManagementController@roles_user')->name('user.roles');
        Route::post('user/{id}/permissions', 'UserManagementController@save_permissions_user')->name('user.permissions.save');
        Route::post('user/{id}/roles', 'UserManagementController@save_roles_user')->name('user.roles.save');

        //Permissions Routes
        Route::get('permissions', 'UserManagementController@permissions')->name('permissions');
        Route::get('permission/add', 'UserManagementController@add_permission')->name('permission.add');
        Route::get('permission/{id}', 'UserManagementController@view_permission')->name('permission.view');
        Route::post('permission/add', 'UserManagementController@save_permission')->name('permission.save');
        Route::get('permission/{id}/edit', 'UserManagementController@edit_permission')->name('permission.edit');
        Route::put('permission/{id}/update', 'UserManagementController@update_permission')->name('permission.update');
        Route::delete('permission/{id}/delete', 'UserManagementController@delete_permission')->name('permission.delete');

        //Roles Routes
        Route::get('roles', 'UserManagementController@roles')->name('roles');
        Route::get('role/add', 'UserManagementController@add_role')->name('role.add');
        Route::get('role/{id}', 'UserManagementController@view_role')->name('role.view');
        Route::post('role/add', 'UserManagementController@save_role')->name('role.save');
        Route::get('role/{id}/edit', 'UserManagementController@edit_role')->name('role.edit');
        Route::put('role/{id}/update', 'UserManagementController@update_role')->name('role.update');
        Route::delete('role/{id}/delete', 'UserManagementController@delete_role')->name('role.delete');

    });


});
//
//Claimants Routes
Route::get('claimants', 'ClaimantController@getClaimants')->name('claimants');
Route::get('claimants/add', 'ClaimantController@add_claimant')->name('claimant.add');
Route::post('claimants/save', 'ClaimantController@saveClaimant')->name('claimant.save');
Route::get('claimants/{id}', 'ClaimantController@viewClaimant')->name('claimant.view');
Route::delete('claimants/{id}/delete', 'ClaimantController@deleteClaimant')->name('claimant.delete');
Route::get('claimants/{id}/edit', 'ClaimantController@editClaimant')->name('claimant.edit');
Route::put('claimants/{id}/update', 'ClaimantController@updateClaimant')->name('claimant.update');

//      Claims Route
Route::get('claims', 'ClaimsController@getClaims')->name('claims');
Route::post('claims', 'ClaimsController@updateStatus')->name('update_claim_status');
Route::post('process-claims', 'ClaimsController@processClaim')->name('process-claim');
Route::post('approve-claims', 'ClaimsController@approveClaim')->name('approve-claim');
Route::post('decline-claims', 'ClaimsController@declineClaim')->name('decline-claim');
Route::get('claims/{id}', 'ClaimsController@viewClaim')->name('claims.view');

//Broker Route
Route::get('broker', 'BrokerController@getBrokers')->name('brokers');
Route::get('broker/add', 'BrokerController@addBrokers')->name('broker.add');
Route::post('broker/add', 'BrokerController@saveBrokers')->name('broker.save');
Route::get('broker/{id}', 'BrokerController@viewBrokers')->name('broker.view');
Route::delete('broker/{id}/delete', 'BrokerController@deleteBrokers')->name('broker.delete');
Route::get('broker/{id}/edit', 'BrokerController@editBrokers')->name('broker.edit');
Route::put('broker/{id}/update', 'BrokerController@updateBrokers')->name('broker.update');


Route::get('scrape', 'BrokerController@scrapeWeb')->name('scrape');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserManagementController.php
<?php

namespace App\Http\Controllers;

use App\Permission;
use App\Role;
use App\User;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserManagementController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Shows the list of user (10 per page).
     *
     * @return \Illuminate\Http\Response
     */
    public function users()
    {
        $users = User::paginate(10);;
        return view('user-management.users.index', compact('users'));
    }

    /**
     * Add a user
     *
     * @return \Illuminate\Http\Response
     */
    public function add_user()
    {

        $roles = Role::all();

        return view('user-management.users.add', compact('roles'));
    }

    /**
     * Save new a user
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function save_user(Request $request)
    {

        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);


//        //We assign a then assign a role and permissions to a user
//        $role = Role::where('name', $request->input('role'))->first();
//        if (!empty($role)) {
//            $user->attachRole($role);
//        }

        $request->session()->flash('status', [
            'error' => false,
            'title' => 'Great!',
            'message' => 'New user added.',
        ]);


        return redirect()->route('manage.users');
    }

    /**
     * Opens the user page.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function view_user($id)
    {
        $user = User::find($id);
        return view('user-management.users.view', compact('user'));
    }

    /**
     * Opens the edit user page.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit_user($id)
    {
        $user = User::find($id);
        return view('user-management.users.edit', compact('user'));
    }

    /**
     * Delete User Account.
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function delete_user(Request $request, $id)
    {
        User::destroy($id);


        $request->session()->flash('status', [
            'error' => false,
            'title' => 'Great!',
            'message' => 'User Deleted.',
        ]);

        return back();
    }

    /**
     * Updates user information.
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update_user(Request $request, $id)
    {

        $this->validate($request, [
            'name' => 'required|min:2|string',
            'email' => 'required|min:2|email|unique:users,email,' . $id,
        ]);

        $user = User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->save();

        $request->session()->flash('status', [
            'error' => false,
            'title' => 'Great!',
            'message' => 'User Updated.',
        ]);

        return redirect()->route('manage.users');
    }

//    ****************PERMISSIONS*******************

    /**
     * List all the permissions.
     *
     * @return \Illuminate\Http\Response
     */
    public function permissions()
    {
        $permissions = Permission::paginate(10);
        return view('user-management.permissions.index', compact('permissions'));
    }

    /**
     * Opens the permission information page.
     *
     * @return \Illuminate\Http\Response
     */
    public function view_permission($id)
    {
        $permission = Permission::find($id);
        return view('user-management.permissions.view', compact('permission'));
    }

    /**
     * Create permissions.
     *
     * @return \Illuminate\Http\Response
     */
    public function add_permission()
    {

        return view('user-management.permissions.add');
    }

    /**
     * List all the permissions.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */

    public function save_permission(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:permissions,name|string|min:3',
            'display_name' => 'nullable|string|min:3',
            'description' => 'nullable|string|min:3'
        ]);
        try {
            $createPermission = new Permission();
            $createPermission->name = str_slug(strtolower($request->name));
            $createPermission->display_name = $request->display_name; // optional
            $createPermission->description = $request->description; // optional
            $createPermission->save();

            $request->session()->flash('status', [
                'error' => false,
                'title' => 'Great!',
                'message' => 'New permission added.',
            ]);

            return redirect()->route('manage.permissions');


        } catch (QueryException $ex) {

            $request->session()->flash('status', [
                'error' => true,
                'title' => 'Sorry!',
                'message' => 'Issue adding permission.',
            ]);

            return back();
        }
    }

    /**
     * Edit a permissions.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function edit_permission($id)
    {
        $permission = Permission::find($id);
        return view('user-management.permissions.edit', compact('permission'));
    }

    /**
     * Update a permissions.
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update_permission(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|unique:permissions,name,' . $id . '|string|min:3',
            'display_name' => 'nullable|string|min:3',
            'description' => 'nullable|string|min:3'
        ]);

        try {
            $updatePermission = Permission::find($id);
            $updatePermission->name = str_slug(strtolower($request->name));
            $updatePermission->display_name = $request->display_name; // optional
            $updatePermission->description = $request->description; // optional
            $updatePermission->save();


            $request->session()->flash('status', [
                'error' => false,
                'title' => 'Great!',
                'message' => 'Permission updated.',
            ]);

            return redirect()->route('manage.permissions');
        } catch (QueryException $ex) {

            $request->session()->flash('status', [
                'error' => true,
                'title' => 'Sorry!',
                'message' => 'Issue updating permission.',
            ]);

            return back();
        }
    }

    /**
     * Delete Permission.
     *
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function delete_permission(Request $request, $id)
    {
        Permission::destroy($id);

        $request->session()->flash('status', [
            'error' => false,
            'title' => 'Great!',
            'message' => 'Permission Deleted!',
        ]);

        return back();
    }



    //********************ROLES*******************************

    /**
     * All roles page.
     *
     * @return \Illuminate\Http\Response
     */
    public function roles()
    {
        $roles = Role::paginate(10);
        return view('user-management.roles.index', compact('roles'));
    }

    /**
     * View role details.
     *
     * @param $id
     * @return \Illuminate\Http\Response
     */
    public function view_role($id)
    {
        $role = Role::find($id);

        return view('user-management.roles.view', compact('role'));
    }

    /**
     * Add a new role page.
     *
     * @return \Illuminate\Http\Response
     */
    public function add_role()
    {
        $permissions = Permission::all();
        return view('user-management.roles.add', compact('permissions'));
    }

    /**
     * Save new role details.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function save_role(Request $request)
    {
//    return $request->all();
        $request->name = str_slug(strtolower($request->name));

        $this->validate($request, [
            'name' => 'required|string|min:2|unique:roles,name',
            'display_name' => 'nullable|string|min:2',
            'description' => 'nullable|string|min:3',
            'permissions' => 'required|array|min:1',
            'permissions.*' => 'required|numeric|min:1'
        ]);

        try {
            $owner = new Role();
            $owner->name = $request->name;
            $owner->display_name = $request->display_name;
            $owner->description = $request->description;
            $owner->save();

            $owner->attachPermissions($request->permissions);

            $request->session()->flash('status', [
                'error' => false,
                'title' => 'Great!',
                'message' => 'New role added!',
            ]);

            return redirect()->route('manage.roles');
        } catch (QueryException $ex) {

resources/views/user-management/users/add.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-6 col-12 mb-2">
                <h3 class="content-header-title mb-0">Users</h3>
            </div>
        </div>
        <div class="content-body">
            <section id="configuration">
                <div class="row">
                    <div class="col-12">
                        <div class="card">

                            <div class="card-header">
                                <h4 class="card-title">Add User</h4>
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                        {{--<li><a data-action="expand"><i class="ft-maximize"></i></a></li>--}}
                                    </ul>
                                </div>
                            </div>

                            <div class="card-content collapse show">
                                <div class="card-body card-dashboard">

                                    @if (session('status'))
                                        <div class="alert {{ (session()->get("status.error")) ? "alert-danger" : "alert-success"}}"
                                             role="alert" style="margin-top: -25px; margin-bottom: 25px;">
                                            <strong>{{session()->get("status.title")}}</strong> {{session()->get("status.message")}}
                                        </div>
                                    @endif

                                    <form method="POST" action="{{ route('manage.user.save') }}">
                                        @csrf

                                        <div class="form-group row">
                                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                            <div class="col-md-6">
                                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                                @if ($errors->has('name'))
                                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                            <div class="col-md-6">
                                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                                @if ($errors->has('email'))
                                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                                @endif
                                            </div>
                                        </div>





                                        <div class="form-group row">
                                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                            <div class="col-md-6">
                                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                                @if ($errors->has('password'))
                                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                                            <div class="col-md-6">
                                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                                            </div>
                                        </div>

                                        <div class="form-group row mb-0">
                                            <div class="col-md-6 offset-md-4">
                                                <button type="submit" class="btn btn-primary mr-2">
                                                    {{ __('Add') }}
                                                </button>
                                                <a href="{{URL::previous()}}" class="btn btn-secondary left">
                                                    {{ __('Back') }}
                                                </a>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/user-management/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-6 col-12 mb-2">
                <h3 class="content-header-title mb-0">Users</h3>
            </div>

            <div class="content-header-right col-md-6 col-12">
                <div class="media width-250 float-right">
                    <div class="media-body media-right text-right">
                        <button type="button" class="btn btn-float btn-primary"
                                style="padding: 8px 8px; width: 150px">
                            <a href="{{route('manage.user.add')}}" style="padding: 10px; color: #ffffff">ADD USER</a>
                        </button>
                    </div>
                </div>
            </div>

        </div>
        <div class="content-body">
            <section id="configuration">
                <div class="row">
                    <div class="col-12">
                        <div class="card">

                            <div class="card-header">
                                <h4 class="card-title">Showing All Users</h4>
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                        <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                                    </ul>
                                </div>
                            </div>

                            <div class="card-content collapse show">
                                <div class="card-body card-dashboard">


                                    @if (session('status'))
                                        <div class="alert {{ (session()->get("status.error")) ? "alert-danger" : "alert-success"}}" role="alert" style="margin-top: -25px; margin-bottom: 25px;">
                                            <strong>{{session()->get("status.title")}}</strong> {{session()->get("status.message")}}
                                        </div>
                                    @endif

                                    <table class="table table-striped table-bordered">
                                        <thead>
                                        <tr>
                                            <th scope="col">Name</th>
                                            <th scope="col">email</th>
                                            <th scope="col">Date Created</th>
                                            <th scope="col" width="230px">Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($users as $user)
                                            <tr>
                                                <td>{{$user->name}}</td>
                                                <td>{{$user->email}}</td>
                                                <td>{{date('M d, Y',strtotime($user->created_at))}}</td>
                                                <td>
                                                    <a href="{{route('manage.user.edit',[$user->id])}}"
                                                       class="btn btn-secondary btn-sm">
                                                        <i class="icon-check"></i> Edit
                                                    </a>
                                                    <a class="dropdow-item btn btn-danger btn-sm"
                                                       href="{{ route('manage.user.delete',[$user->id]) }}"
                                                       onclick="event.preventDefault();
                                                     document.getElementById('delete-form').submit();">
                                                        {{ __('Delete') }}
                                                    </a>

                                                    <form id="delete-form"
                                                          action="{{ route('manage.user.delete',[$user->id]) }}"
                                                          method="POST" style="display: none;">
                                                        @csrf {{method_field('DELETE')}}
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{ $users->links() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
@endsection

resources/views/user-management/users/permissions.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-wrapper">

        <div class="content-header row">
            <div class="content-header-left col-md-6 col-12 mb-2">
                <h3 class="content-header-title mb-0">Users</h3>
            </div>
        </div>

        <div class="content-body">
            <section id="configuration">
                <div class="row">
                    <div class="col-12">

                        <div class="card">


                            <div class="card-header">
                                <h4 class="card-title">Set permissions for *{{$user->name}}</h4>
                                <a class="heading-elements-toggle"><i class="fa fa-ellipsis-v font-medium-3"></i></a>
                                <div class="heading-elements">
                                    <ul class="list-inline mb-0">
                                        <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                        {{--<li><a data-action="expand"><i class="ft-maximize"></i></a></li>--}}
                                    </ul>
                                </div>
                            </div>

                            <div class="card-content collapse show">
                                <div class="card-body card-dashboard">


                                    @if (session('status'))
                                        <div class="alert {{ (session()->get("status.error")) ? "alert-danger" : "alert-success"}}"
                                             role="alert" style="margin-top: -25px; margin-bottom: 25px;">
                                            <strong>{{session()->get("status.title")}}</strong> {{session()->get("status.message")}}
                                        </div>
                                    @endif

                                    <form method="POST"
                                          action="{{ route('manage.user.permissions.save',[$user->id]) }}">
                                        @csrf
                                        <h6>Permissions</h6>
                                        <div class="form-group row">
                                            @foreach($permissions as $permission)
                                                <div class="col-md-3">
                                                    <div class="form-check mb-3">
                                                        <input class="form-check-input"
                                                               @if(in_array($permission->id,$user_permissions)) checked
                                                               @endif
                                                               type="checkbox" name="permissions[]"
                                                               value="{{$permission->id}}"
                                                               id="Check{{$permission->id}}">
                                                        <label class="form-check-label" for="Check{{$permission->id}}">
                                                            {{$permission->display_name}}
                                                        </label>
                                                    </div>
                                                </div>
                                            @endforeach
                                        </div>

                                        <div class="form-group row mb-0">
                                            <div class="col-md-6 offset-md-4">
                                                <button type="submit" class="btn btn-primary mr-md-3">
                                                    {{ __('Save') }}
                                                </button>
                                                <a href="{{URL::previous()}}" class="btn btn-secondary left">
                                                    {{ __('Back') }}
                                                </a>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </section>
        </div>
    </div>
@endsection